include required("/stdlib/jdk/21/azul.conf")
#include required("/stdlib/jvm/javafx/from-maven.conf")
include required("/stdlib/jvm/enhancements/client/v1.conf")

app {
  display-name = "Pixel DNG Fixer"
  fsname = "pixeldngfixer"
  vcs-url = "https://github.com/qligier/PixelDngFixer"
  license = MIT
  icons = "icons/icons-*.png"
  version = "1.0.4"
  machines = [
      windows.amd64, linux.amd64.glibc, mac.amd64, mac.aarch64
    ]

  inputs += target/pixel-dng-fixer-1.0.4.jar

  site {
    base-url = "https://github.com/qligier/PixelDngFixer/releases/latest/download"
  }

}

conveyor.compatibility-level = 19
